require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

source 'https://cdn.cocoapods.org/'

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PMUForms' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name == 'stripe-react-native'
        def pod.build_type
          Pod::BuildType.static_framework
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['REACT_NATIVE_PATH'] = '$(SRCROOT)/../../node_modules/react-native'
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-elaborated-enum-base'
      end

      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
        end
      end

      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_CONSTEVAL='
        end
      end

      if target.name == 'stripe-react-native'
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xfrontend -disable-objc-attr-requires-foundation-module'
        end
      end
    end
  end
end